use_frameworks!

target 'SpriteKitSeeThrough_Example' do
  pod 'SpriteKitSeeThrough', :path => '../'

  target 'SpriteKitSeeThrough_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
