use_frameworks!

target 'SpriteKitSeeThrough_Example' do
  pod 'SpriteKitSeeThrough', :path => '../'

  target 'SpriteKitSeeThrough_Tests' do
    inherit! :search_paths

    pod 'Nimble', '5.1.0'
    pod 'Quick', '0.10.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each  do |target|
      target.build_configurations.each  do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
   end
end
